"""Tests for core.improve_backlog -- shadcn/improve backlog federation adapter."""

from __future__ import annotations

from pathlib import Path

from core.improve_backlog import (
    build_entities,
    parse_index,
    parse_plan_status,
    sync,
)
from core.l6_store import L6Store

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------

_INDEX = """\
# Implementation Plans

Generated by an advisor agent, following the shadcn/improve plan format.

## Execution order & status

| Plan | Title | Priority | Effort | Depends on | Status |
|------|-------|----------|--------|------------|--------|
| 001  | Wire the frobnicator | P1 | M | — | DONE |
| 002  | Ship the doodad | P2 | S | 001 | TODO |
| 003  | Refactor the gizmo | P1 | L | 001, 002 | BLOCKED (waiting on upstream #42) |

## Dependency notes

- None yet.

## Findings considered and rejected

- Implement as a participants/ class: rejected for v1.
- Sync via the MCP transport: rejected — times out on
  long writes today.
"""

_PLAN_001 = """\
# Plan 001: Wire the frobnicator

## Status

- **Priority**: P1
- **Effort**: M
- **Risk**: LOW
- **Depends on**: none
- **Category**: direction
- **Planned at**: commit `ab49132`, 2026-06-10

## Steps

Irrelevant body text.
"""

_PLAN_002_PARTIAL = """\
# Plan 002: Ship the doodad

## Status

- **Priority**: P2

## Steps

Status block is partial on purpose.
"""


def _write_repo(tmp_path: Path, index: str = _INDEX) -> Path:
    repo = tmp_path / "frob-repo"
    plans = repo / "plans"
    plans.mkdir(parents=True)
    (plans / "README.md").write_text(index, encoding="utf-8")
    (plans / "001-wire-the-frobnicator.md").write_text(_PLAN_001, encoding="utf-8")
    (plans / "002-ship-the-doodad.md").write_text(_PLAN_002_PARTIAL, encoding="utf-8")
    # plan 003 has an index row but no plan file -- deliberately missing.
    return repo


def _library(tmp_path: Path) -> Path:
    library = tmp_path / "agent-library"
    (library / "agents").mkdir(parents=True)
    return library


# ---------------------------------------------------------------------------
# parse_index
# ---------------------------------------------------------------------------


def test_parse_index_well_formed(tmp_path):
    repo = _write_repo(tmp_path)
    index = parse_index(repo / "plans" / "README.md")
    assert [row.plan for row in index.rows] == ["001", "002", "003"]
    row = index.rows[0]
    assert row.title == "Wire the frobnicator"
    assert row.priority == "P1"
    assert row.effort == "M"
    assert row.status == "done"
    assert index.rows[1].depends_on == "001"


def test_parse_index_blocked_reason_captured(tmp_path):
    repo = _write_repo(tmp_path)
    index = parse_index(repo / "plans" / "README.md")
    blocked = index.rows[2]
    assert blocked.status == "blocked"
    assert blocked.status_reason == "waiting on upstream #42"


def test_parse_index_extra_column_tolerated(tmp_path):
    index_md = """\
## Execution order & status

| Plan | Owner | Title | Priority | Effort | Depends on | Status |
|------|-------|-------|----------|--------|------------|--------|
| 001  | mac   | Wire the frobnicator | P1 | M | — | TODO |
"""
    repo = tmp_path / "repo"
    (repo / "plans").mkdir(parents=True)
    (repo / "plans" / "README.md").write_text(index_md, encoding="utf-8")
    index = parse_index(repo / "plans" / "README.md")
    assert len(index.rows) == 1
    assert index.rows[0].plan == "001"
    assert index.rows[0].title == "Wire the frobnicator"
    assert index.rows[0].status == "todo"


def test_parse_index_rejected_findings_bullets(tmp_path):
    repo = _write_repo(tmp_path)
    index = parse_index(repo / "plans" / "README.md")
    assert len(index.rejected_findings) == 2
    assert index.rejected_findings[0].startswith("Implement as a participants/")
    # Wrapped bullet lines are joined.
    assert "times out on long writes today." in index.rejected_findings[1]


# ---------------------------------------------------------------------------
# parse_plan_status
# ---------------------------------------------------------------------------


def test_parse_plan_status_full_block(tmp_path):
    repo = _write_repo(tmp_path)
    meta = parse_plan_status(repo / "plans" / "001-wire-the-frobnicator.md")
    assert meta.stem == "001-wire-the-frobnicator"
    assert meta.priority == "P1"
    assert meta.effort == "M"
    assert meta.risk == "LOW"
    assert meta.depends_on == "none"
    assert meta.category == "direction"
    assert meta.planned_commit == "ab49132"
    assert meta.planned_date == "2026-06-10"


def test_parse_plan_status_partial_block_no_raise(tmp_path):
    repo = _write_repo(tmp_path)
    meta = parse_plan_status(repo / "plans" / "002-ship-the-doodad.md")
    assert meta.priority == "P2"
    assert meta.risk is None
    assert meta.planned_commit is None


# ---------------------------------------------------------------------------
# build_entities
# ---------------------------------------------------------------------------


def test_build_entities_missing_plan_file_no_crash(tmp_path):
    repo = _write_repo(tmp_path)
    library = _library(tmp_path)
    result = sync(repo, library)
    # Plan 003 has no plan file: entity name falls back to the plan number.
    store = L6Store(library)
    manifest = store.get_agent_manifest("improve", access_level="public")
    names = {e["name"] for e in manifest["known_entities"]}
    assert "plan:frob-repo/003" in names
    assert result["entities_added"] == 4  # 3 plans + rollup


def test_rollup_counts_and_next_executable(tmp_path):
    repo = _write_repo(tmp_path)
    index = parse_index(repo / "plans" / "README.md")
    metas = {
        "001": parse_plan_status(repo / "plans" / "001-wire-the-frobnicator.md"),
        "002": parse_plan_status(repo / "plans" / "002-ship-the-doodad.md"),
        "003": None,
    }
    entities = build_entities("frob-repo", index, metas)
    rollup = next(e for e in entities if e["name"] == "improve-backlog:frob-repo")
    # 002 is the lowest-numbered TODO whose only dep (001) is DONE.
    assert "Next executable plan: 002" in rollup["summary"]
    assert "1 done" in rollup["summary"]
    assert "1 blocked" in rollup["summary"]


def test_plan_entity_summary_carries_status_and_reason(tmp_path):
    repo = _write_repo(tmp_path)
    index = parse_index(repo / "plans" / "README.md")
    entities = build_entities("frob-repo", index, {"001": None, "002": None, "003": None})
    blocked = next(e for e in entities if e["name"] == "plan:frob-repo/003")
    assert "BLOCKED" in blocked["summary"]
    assert "reason: waiting on upstream #42" in blocked["summary"]
    assert "blocked" in blocked["tags"]


def test_next_executable_skipped_when_deps_not_done():
    from core.improve_backlog import BacklogRow, _next_executable

    rows = [
        BacklogRow(plan="001", title="a", status="todo", depends_on="—"),
        BacklogRow(plan="002", title="b", status="todo", depends_on="001"),
    ]
    nxt = _next_executable(rows)
    assert nxt is not None and nxt.plan == "001"
    rows[0].status = "in progress"
    # 002's dep is not DONE and 001 is no longer TODO -> nothing executable.
    assert _next_executable(rows) is None


# ---------------------------------------------------------------------------
# sync
# ---------------------------------------------------------------------------


def test_entity_names_stable_across_two_syncs(tmp_path):
    repo = _write_repo(tmp_path)
    library = _library(tmp_path)
    first = sync(repo, library)
    assert first["entities_added"] == 4
    second = sync(repo, library)
    # Merge-dedupe by name: second sync updates, never re-adds.
    assert second["entities_added"] == 0
    assert second["entities_updated"] == 4
    assert second["total_entities"] == 4


def test_dry_run_performs_no_write(tmp_path, capsys):
    repo = _write_repo(tmp_path)
    library = _library(tmp_path)
    payload = sync(repo, library, dry_run=True)
    assert payload["dry_run"] is True
    out = capsys.readouterr().out
    assert "plan:frob-repo/001-wire-the-frobnicator" in out
    assert list((library / "agents").iterdir()) == []  # library dir untouched


def test_dry_run_survives_narrow_codepage_stdout(tmp_path, monkeypatch, capsys):
    """cp1252 consoles can't encode e.g. U+2192; dry-run must degrade, not crash."""
    import builtins

    repo = _write_repo(tmp_path)
    plans = repo / "plans"
    index = (plans / "README.md").read_text(encoding="utf-8")
    (plans / "README.md").write_text(
        index.replace("Wire the frobnicator", "Wire → frobnicator"), encoding="utf-8"
    )
    library = _library(tmp_path)

    real_print = builtins.print
    calls = {"n": 0}

    def cp1252_print(*args, **kwargs):
        calls["n"] += 1
        if calls["n"] == 1:
            # Simulate a console that cannot encode the arrow.
            str(args[0]).encode("cp1252")
        real_print(*args, **kwargs)

    monkeypatch.setattr(builtins, "print", cp1252_print)
    payload = sync(repo, library, dry_run=True)
    assert payload["dry_run"] is True
    out = capsys.readouterr().out
    assert "frobnicator" in out  # fallback actually printed
    assert list((library / "agents").iterdir()) == []


def test_sync_round_trips_through_l6store(tmp_path):
    repo = _write_repo(tmp_path)
    library = _library(tmp_path)
    summary = sync(repo, library)
    assert summary["agent_id"] == "improve"
    assert summary["sessions_added"] == 1

    store = L6Store(library)
    manifest = store.get_agent_manifest("improve", access_level="public")
    assert manifest["agent"]["type"] == "other"
    names = {e["name"] for e in manifest["known_entities"]}
    assert "plan:frob-repo/001-wire-the-frobnicator" in names
    assert "improve-backlog:frob-repo" in names
    session = manifest["recent_sessions"][0]
    assert session["project_focus"] == ["frob-repo", "improve-backlog"]
    assert session["key_actions"][0].startswith("synced 3 plans:")
